"""
Article 10 - Data governance.

Validates that the feature distributions seen in production remain
consistent with the training data profile. When significant divergence
is detected, writes an alert to alerts.data_quality.

The training profile is loaded from a JSON file at startup. In a full
deployment this would be generated as part of the model training pipeline
and stored alongside the model artifact.

Detection uses simple range checks and categorical distribution checks.
This is intentionally conservative - the goal is to catch genuine data
quality issues (missing fields, out-of-range values, unexpected categories)
not to flag minor statistical fluctuations.
"""

import json
import logging
import os
import uuid
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from typing import Optional

from kafka import KafkaConsumer, KafkaProducer

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

KAFKA_BOOTSTRAP = os.getenv("KAFKA_BOOTSTRAP", "localhost:9092")
INPUT_TOPIC = "otel.spans"
OUTPUT_TOPIC = "alerts.data_quality"
CONSUMER_GROUP = "data-quality-checker"
PROFILE_PATH = os.getenv("TRAINING_PROFILE_PATH", "pipeline/training_profile.json")

# Check distributions every N observations per model.
CHECK_INTERVAL = 50


@dataclass
class DataQualityAlert:
    alert_id: str
    model_id: str
    check_type: str
    feature_name: str
    expected: str
    observed: str
    observation_count: int
    detected_at: str
    eu_ai_act_article: str = "10"
    severity: str = "warning"

    def to_json(self) -> str:
        return json.dumps(asdict(self))


def load_training_profile(path: str) -> dict:
    """
    Loads the training data profile. If the file doesn't exist,
    returns a minimal default profile for the health-triage-v2 model.

    In production this file is generated by the training pipeline
    and checked into the model registry alongside the model weights.
    """
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)

    log.warning("training profile not found at %s, using default", path)
    return {
        "health-triage-v2": {
            "features": {
                "age_band": {
                    "type": "categorical",
                    "allowed_values": ["0-5", "6-17", "18-40", "41-65", "65+"],
                    "max_unknown_rate": 0.02,
                },
                "symptom_severity": {
                    "type": "continuous",
                    "min": 0.0,
                    "max": 1.0,
                    "max_out_of_range_rate": 0.01,
                },
                "days_symptomatic": {
                    "type": "continuous",
                    "min": 0,
                    "max": 90,
                    "max_out_of_range_rate": 0.01,
                },
            }
        }
    }


class FeatureQualityMonitor:
    def __init__(self, model_id: str, profile: dict):
        self.model_id = model_id
        self.profile = profile
        self.observations = 0
        self.feature_counts: dict[str, int] = defaultdict(int)
        self.feature_violations: dict[str, int] = defaultdict(int)
        self.categorical_seen: dict[str, Counter] = defaultdict(Counter)

    def record(self, features: dict) -> list[DataQualityAlert]:
        self.observations += 1

        for fname, fspec in self.profile.get("features", {}).items():
            value = features.get(fname)
            self.feature_counts[fname] += 1

            if value is None:
                self.feature_violations[f"{fname}_missing"] += 1
                continue

            if fspec["type"] == "categorical":
                self.categorical_seen[fname][str(value)] += 1

            elif fspec["type"] == "continuous":
                try:
                    v = float(value)
                    if v < fspec["min"] or v > fspec["max"]:
                        self.feature_violations[f"{fname}_out_of_range"] += 1
                except (TypeError, ValueError):
                    self.feature_violations[f"{fname}_type_error"] += 1

        if self.observations % CHECK_INTERVAL == 0:
            return self._check()

        return []

    def _check(self) -> list[DataQualityAlert]:
        alerts = []

        for fname, fspec in self.profile.get("features", {}).items():
            total = self.feature_counts.get(fname, 0)
            if total == 0:
                continue

            if fspec["type"] == "categorical":
                allowed = set(fspec["allowed_values"])
                seen = self.categorical_seen.get(fname, Counter())
                unknown = sum(v for k, v in seen.items() if k not in allowed)
                unknown_rate = unknown / total

                if unknown_rate > fspec.get("max_unknown_rate", 0.02):
                    alerts.append(DataQualityAlert(
                        alert_id=str(uuid.uuid4()),
                        model_id=self.model_id,
                        check_type="categorical_unknown_rate",
                        feature_name=fname,
                        expected=f"unknown_rate <= {fspec['max_unknown_rate']}",
                        observed=f"unknown_rate = {unknown_rate:.4f}",
                        observation_count=total,
                        detected_at=datetime.now(timezone.utc).isoformat(),
                    ))

            elif fspec["type"] == "continuous":
                violation_key = f"{fname}_out_of_range"
                violations = self.feature_violations.get(violation_key, 0)
                violation_rate = violations / total

                if violation_rate > fspec.get("max_out_of_range_rate", 0.01):
                    alerts.append(DataQualityAlert(
                        alert_id=str(uuid.uuid4()),
                        model_id=self.model_id,
                        check_type="continuous_out_of_range",
                        feature_name=fname,
                        expected=f"[{fspec['min']}, {fspec['max']}] violation_rate <= {fspec['max_out_of_range_rate']}",
                        observed=f"violation_rate = {violation_rate:.4f} over {total} observations",
                        observation_count=total,
                        detected_at=datetime.now(timezone.utc).isoformat(),
                    ))

        return alerts


def extract_features_from_span(raw_value: str) -> list[dict]:
    """
    The agent hashes input features for privacy, so we can't recover
    the raw feature values from the span. Instead we check the span
    attributes that are proxies for feature quality:
    - prediction_score range
    - latency (proxy for input complexity)
    - risk_band distribution

    For a real deployment, the agent would emit feature distribution
    summaries as separate metrics rather than per-span attributes.
    This is noted as a known limitation.
    """
    try:
        payload = json.loads(raw_value)
        results = []

        for rs in payload.get("resourceSpans", []):
            resource_attrs = {
                a["key"]: list(a["value"].values())[0]
                for a in rs.get("resource", {}).get("attributes", [])
            }
            for scope_span in rs.get("scopeSpans", []):
                for span in scope_span.get("spans", []):
                    span_attrs = {
                        a["key"]: list(a["value"].values())[0]
                        for a in span.get("attributes", [])
                    }
                    merged = {**resource_attrs, **span_attrs}
                    model_id = merged.get("ai.model.system_id")
                    score = merged.get("ai.inference.prediction_score")
                    latency = merged.get("ai.inference.latency_ms")

                    if model_id and score is not None:
                        results.append({
                            "model_id": model_id,
                            "features": {
                                "symptom_severity": score,
                                "days_symptomatic": min(latency / 5.0, 90) if latency else None,
                            }
                        })

        return results

    except (json.JSONDecodeError, KeyError):
        return []


def run() -> None:
    profile = load_training_profile(PROFILE_PATH)

    consumer = KafkaConsumer(
        INPUT_TOPIC,
        bootstrap_servers=KAFKA_BOOTSTRAP,
        group_id=CONSUMER_GROUP,
        auto_offset_reset="earliest",
        value_deserializer=lambda v: v.decode("utf-8"),
    )

    producer = KafkaProducer(
        bootstrap_servers=KAFKA_BOOTSTRAP,
        value_serializer=lambda v: v.encode("utf-8"),
    )

    monitors: dict[str, FeatureQualityMonitor] = {}

    log.info("data quality monitor started bootstrap=%s", KAFKA_BOOTSTRAP)

    for message in consumer:
        records = extract_features_from_span(message.value)

        for record in records:
            model_id = record["model_id"]
            features = record["features"]

            if model_id not in monitors:
                model_profile = profile.get(model_id, profile.get("health-triage-v2", {}))
                monitors[model_id] = FeatureQualityMonitor(model_id, model_profile)
                log.info("quality monitor registered model=%s", model_id)

            alerts = monitors[model_id].record(features)

            for alert in alerts:
                producer.send(OUTPUT_TOPIC, value=alert.to_json())
                producer.flush()
                log.warning(
                    "data quality alert model=%s check=%s feature=%s observed=%s",
                    alert.model_id,
                    alert.check_type,
                    alert.feature_name,
                    alert.observed,
                )


if __name__ == "__main__":
    run()
